openapi: 3.0.0
info:
  title: Inventory Web Service

  description: A simple web service with CRUD functionality for managing product inventory.
  version: 0.0.1
servers:
  - url: 'http://localhost:7003'
    description: Local dev server
paths:
  /inventory:
    post:
      summary: Creates a new product inventory.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryViewModel'
      responses:
        '201':
          description: An InventoryViewModel object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryViewModel'
        '400':
          description: Invalid request syntax.
        '422':
          description: List of 1 or more errors if required fields are missing or violate JSR 303 validation.
    get:
      summary: Retrieves all inventories
      responses:
        '200':
          description: Inventory list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryViewModel'
        '404':
          description: Request not found.
  /inventory/{id}:
    # GET, DELETE, and PUT are all under this path entry
    get:
      summary: Retrieves the inventory information by id.
      parameters:
        - name: id
          in: path
          required: true
          description: id of the inventory you would like to retrieve.
          schema:
            type: integer
      responses:
        '200':
          description: InventoryViewModel object matching given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryViewModel'
        '404':
          description: Request not found.

    put:
      summary: Updates an existing inventory
      parameters:
        - name: id
          in: path
          required: true
          description: id of the inventory you would like to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryViewModel'
      responses:
        '201':
          description: Updated
        '400':
          description: Invalid request syntax.
        '422':
          description: Incomplete inventory information. One or more required fields missing.

    delete:
      summary: Deletes an inventory based on the id
      parameters:
        - name: id
          in: path
          required: true
          description: Id of the inventory you would like to delete.
          schema:
            type: integer
      responses:
        '200':
          description: Inventory successfully deleted.

  /inventory/product/{id}:
    get:
      summary: Retrieve inventories by product.
      parameters:
        - name: id
          in: path
          required: true
          description: Product id of inventories you would like to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: List of inventories matching given productId.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryViewModel'
    delete:
      summary: Deletes all inventories with matching productId
      parameters:
        - name: id
          in: path
          required: true
          description: Id of the product for the inventories you would like to delete.
          schema:
            type: integer
      responses:
        '200':
          description: Inventories successfully deleted.

components:
  schemas:
    InventoryViewModel:
      type: object
      properties:
        inventoryId:
          type: integer
        productId:
          type: integer
        quantity:
          type: integer
      required:
        - productId
        - quantity